spring: 
  profiles: 
    active: 
       -dev
---
spring: 
  profiles: dev
  application:  
     name: microcloud-config-lyf-dev
---
spring: 
  profiles: test
  application: 
    name: microcloud-config-lyf-test